---
- name: MySQL provisioning play
  hosts: "{{ 'db' if 'db' in groups else 'all' }}"
  gather_facts: false
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  vars_prompt:
    - name: ansible_user
      prompt: "Username"
      default: "vagrant"
      private: false
    
    - name: ansible_ssh_pass
      prompt: "SSH Password"
  
  pre_tasks:
    - name: Gather OS family fact
      setup:
        filter: ansible_os_family
    
  roles:
    - role: tcc_mysql
