---
- name: "Update all packages with DNF"
  when: ansible_os_family | lower == 'redhat' 
  dnf:
    name: '*'
    state: latest

- name: "Update all packages with APT"
  when: ansible_os_family | lower == 'debian'
  apt:
    name: '*'
    state: latest
